### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by crestanigabriel** [crestanigabriel/bank-account-using-threads#2]
- [] Implementar o uso de threads e mutex
- [] Definir função para chamar diversos métodos em Bank
- [] Criar formas de rodar o programa: sem nada, com threads e com threads/mutex (salvar resultados num txt?)
